"""init_all_tables

Revision ID: e5a43c763b9f
Revises: 
Create Date: 2026-06-20 21:57:24.759215

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e5a43c763b9f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('department',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='院系名称'),
    sa.Column('code', sa.String(length=50), nullable=False, comment='院系代码'),
    sa.Column('description', sa.Text(), nullable=True, comment='院系简介'),
    sa.Column('status', sa.SmallInteger(), nullable=False, comment='1=正常 0=停用'),
    sa.Column('is_deleted', sa.Boolean(), nullable=False, comment='软删除标记'),
    sa.Column('deleted_at', sa.DateTime(), nullable=True, comment='删除时间'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('menu',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('parent_id', sa.Integer(), nullable=True, comment='父菜单ID'),
    sa.Column('name', sa.String(length=50), nullable=False, comment='菜单名称'),
    sa.Column('code', sa.String(length=100), nullable=False, comment='权限标识'),
    sa.Column('type', sa.SmallInteger(), nullable=False, comment='1=目录 2=菜单 3=按钮'),
    sa.Column('path', sa.String(length=200), nullable=True, comment='前端路由路径'),
    sa.Column('icon', sa.String(length=50), nullable=True, comment='图标名称'),
    sa.Column('sort_order', sa.Integer(), nullable=False, comment='排序权重'),
    sa.Column('status', sa.SmallInteger(), nullable=False, comment='1=启用 0=禁用'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['parent_id'], ['menu.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('role',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('code', sa.String(length=50), nullable=False, comment='角色代码'),
    sa.Column('name', sa.String(length=50), nullable=False, comment='角色名称'),
    sa.Column('description', sa.String(length=255), nullable=True, comment='角色描述'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('username', sa.String(length=50), nullable=False, comment='登录用户名'),
    sa.Column('password_hash', sa.String(length=255), nullable=False, comment='bcrypt加密密码'),
    sa.Column('real_name', sa.String(length=50), nullable=False, comment='真实姓名'),
    sa.Column('phone', sa.String(length=20), nullable=True, comment='手机号'),
    sa.Column('email', sa.String(length=100), nullable=True, comment='邮箱'),
    sa.Column('id_card', sa.String(length=18), nullable=True, comment='身份证号'),
    sa.Column('avatar', sa.String(length=255), nullable=True, comment='头像URL'),
    sa.Column('status', sa.SmallInteger(), nullable=False, comment='1=正常 0=禁用'),
    sa.Column('must_change_password', sa.Boolean(), nullable=False, comment='首次登录强制改密'),
    sa.Column('last_login_at', sa.DateTime(), nullable=True, comment='最后登录时间'),
    sa.Column('is_deleted', sa.Boolean(), nullable=False, comment='软删除标记'),
    sa.Column('deleted_at', sa.DateTime(), nullable=True, comment='删除时间'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('id_card'),
    sa.UniqueConstraint('phone'),
    sa.UniqueConstraint('username')
    )
    op.create_table('announcement',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('title', sa.String(length=200), nullable=False, comment='公告标题'),
    sa.Column('content', sa.Text(), nullable=False, comment='公告内容'),
    sa.Column('type', sa.SmallInteger(), nullable=False, comment='1=通知 2=活动 3=紧急'),
    sa.Column('publisher_id', sa.Integer(), nullable=False, comment='发布人'),
    sa.Column('is_top', sa.Boolean(), nullable=False, comment='是否置顶'),
    sa.Column('status', sa.SmallInteger(), nullable=False, comment='1=已发布 2=草稿 0=已撤回'),
    sa.Column('published_at', sa.DateTime(), nullable=True, comment='发布时间'),
    sa.Column('is_deleted', sa.Boolean(), nullable=False, comment='软删除标记'),
    sa.Column('deleted_at', sa.DateTime(), nullable=True, comment='删除时间'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['publisher_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('operation_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('user_id', sa.Integer(), nullable=True, comment='操作人'),
    sa.Column('module', sa.String(length=50), nullable=False, comment='模块名'),
    sa.Column('action', sa.String(length=20), nullable=False, comment='操作类型'),
    sa.Column('target_id', sa.Integer(), nullable=True, comment='操作对象ID'),
    sa.Column('detail', sa.Text(), nullable=True, comment='变更详情JSON'),
    sa.Column('ip_address', sa.String(length=50), nullable=True, comment='请求IP'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='操作时间'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('role_menu',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('role_id', sa.Integer(), nullable=False, comment='角色ID'),
    sa.Column('menu_id', sa.Integer(), nullable=False, comment='菜单ID'),
    sa.ForeignKeyConstraint(['menu_id'], ['menu.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('role_id', 'menu_id', name='uq_role_menu')
    )
    op.create_table('teacher',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='关联登录账号'),
    sa.Column('employee_no', sa.String(length=30), nullable=False, comment='工号'),
    sa.Column('name', sa.String(length=50), nullable=False, comment='姓名'),
    sa.Column('gender', sa.SmallInteger(), nullable=False, comment='1=男 2=女'),
    sa.Column('id_card', sa.String(length=18), nullable=False, comment='身份证号'),
    sa.Column('position', sa.String(length=50), nullable=False, comment='岗位'),
    sa.Column('title', sa.String(length=50), nullable=True, comment='职称'),
    sa.Column('department_id', sa.Integer(), nullable=True, comment='所属院系'),
    sa.Column('entry_date', sa.Date(), nullable=True, comment='入职日期'),
    sa.Column('status', sa.SmallInteger(), nullable=False, comment='1=在职 0=离职'),
    sa.Column('is_deleted', sa.Boolean(), nullable=False, comment='软删除标记'),
    sa.Column('deleted_at', sa.DateTime(), nullable=True, comment='删除时间'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['department_id'], ['department.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('employee_no'),
    sa.UniqueConstraint('id_card'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('user_role',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='用户ID'),
    sa.Column('role_id', sa.Integer(), nullable=False, comment='角色ID'),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'role_id', name='uq_user_role')
    )
    op.create_table('announcement_read',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('announcement_id', sa.Integer(), nullable=False, comment='公告ID'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='阅读人'),
    sa.Column('read_at', sa.DateTime(), nullable=False, comment='阅读时间'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['announcement_id'], ['announcement.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('announcement_id', 'user_id', name='uq_announcement_read')
    )
    op.create_table('clazz',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('name', sa.String(length=50), nullable=False, comment='班级名称'),
    sa.Column('code', sa.String(length=50), nullable=False, comment='班级代码'),
    sa.Column('department_id', sa.Integer(), nullable=False, comment='所属院系'),
    sa.Column('grade', sa.String(length=10), nullable=False, comment='年级'),
    sa.Column('counselor_id', sa.Integer(), nullable=True, comment='辅导员'),
    sa.Column('status', sa.SmallInteger(), nullable=False, comment='1=正常 0=停用'),
    sa.Column('is_deleted', sa.Boolean(), nullable=False, comment='软删除标记'),
    sa.Column('deleted_at', sa.DateTime(), nullable=True, comment='删除时间'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['counselor_id'], ['teacher.id'], ),
    sa.ForeignKeyConstraint(['department_id'], ['department.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('course',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='课程名称'),
    sa.Column('code', sa.String(length=50), nullable=False, comment='课程代码'),
    sa.Column('credit', sa.Numeric(precision=3, scale=1), nullable=False, comment='学分'),
    sa.Column('hours', sa.Integer(), nullable=False, comment='学时'),
    sa.Column('course_type', sa.SmallInteger(), nullable=False, comment='1=必修 2=选修 3=公共课'),
    sa.Column('department_id', sa.Integer(), nullable=False, comment='开设院系'),
    sa.Column('teacher_id', sa.Integer(), nullable=True, comment='授课教师'),
    sa.Column('description', sa.Text(), nullable=True, comment='课程简介'),
    sa.Column('status', sa.SmallInteger(), nullable=False, comment='1=正常 0=停用'),
    sa.Column('is_deleted', sa.Boolean(), nullable=False, comment='软删除标记'),
    sa.Column('deleted_at', sa.DateTime(), nullable=True, comment='删除时间'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['department_id'], ['department.id'], ),
    sa.ForeignKeyConstraint(['teacher_id'], ['teacher.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('exam',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='考试名称'),
    sa.Column('course_id', sa.Integer(), nullable=False, comment='关联课程'),
    sa.Column('exam_type', sa.SmallInteger(), nullable=False, comment='1=期中 2=期末 3=补考 4=测验'),
    sa.Column('exam_date', sa.Date(), nullable=False, comment='考试日期'),
    sa.Column('exam_time', sa.String(length=50), nullable=True, comment='考试时间段'),
    sa.Column('location', sa.String(length=100), nullable=True, comment='考试地点'),
    sa.Column('clazz_id', sa.Integer(), nullable=True, comment='参加班级(NULL=全院)'),
    sa.Column('description', sa.Text(), nullable=True, comment='备注'),
    sa.Column('status', sa.SmallInteger(), nullable=False, comment='1=正常 0=取消'),
    sa.Column('is_deleted', sa.Boolean(), nullable=False, comment='软删除标记'),
    sa.Column('deleted_at', sa.DateTime(), nullable=True, comment='删除时间'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['clazz_id'], ['clazz.id'], ),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('student',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='关联登录账号'),
    sa.Column('student_no', sa.String(length=30), nullable=False, comment='学号'),
    sa.Column('name', sa.String(length=50), nullable=False, comment='姓名'),
    sa.Column('gender', sa.SmallInteger(), nullable=False, comment='1=男 2=女'),
    sa.Column('id_card', sa.String(length=18), nullable=False, comment='身份证号'),
    sa.Column('clazz_id', sa.Integer(), nullable=False, comment='所属班级'),
    sa.Column('enrollment_date', sa.Date(), nullable=True, comment='入学日期'),
    sa.Column('status', sa.SmallInteger(), nullable=False, comment='1=在读 2=休学 3=毕业 0=退学'),
    sa.Column('is_deleted', sa.Boolean(), nullable=False, comment='软删除标记'),
    sa.Column('deleted_at', sa.DateTime(), nullable=True, comment='删除时间'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['clazz_id'], ['clazz.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id_card'),
    sa.UniqueConstraint('student_no'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('teacher_clazz',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('teacher_id', sa.Integer(), nullable=False, comment='教职工ID'),
    sa.Column('clazz_id', sa.Integer(), nullable=False, comment='班级ID'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['clazz_id'], ['clazz.id'], ),
    sa.ForeignKeyConstraint(['teacher_id'], ['teacher.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('teacher_id', 'clazz_id', name='uq_teacher_clazz')
    )
    op.create_table('score',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('student_id', sa.Integer(), nullable=False, comment='学生ID'),
    sa.Column('exam_id', sa.Integer(), nullable=False, comment='考试ID'),
    sa.Column('course_id', sa.Integer(), nullable=False, comment='课程ID(冗余)'),
    sa.Column('score', sa.Numeric(precision=5, scale=2), nullable=True, comment='分数'),
    sa.Column('grade', sa.String(length=5), nullable=True, comment='等级A/B/C/D/F'),
    sa.Column('rank_in_class', sa.Integer(), nullable=True, comment='班级排名'),
    sa.Column('remark', sa.String(length=255), nullable=True, comment='备注'),
    sa.Column('scorer_id', sa.Integer(), nullable=True, comment='录入人(教师)'),
    sa.Column('is_deleted', sa.Boolean(), nullable=False, comment='软删除标记'),
    sa.Column('deleted_at', sa.DateTime(), nullable=True, comment='删除时间'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], ),
    sa.ForeignKeyConstraint(['exam_id'], ['exam.id'], ),
    sa.ForeignKeyConstraint(['scorer_id'], ['teacher.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id', 'exam_id', name='uq_score_student_exam')
    )
    op.create_table('student_course',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('student_id', sa.Integer(), nullable=False, comment='学生ID'),
    sa.Column('course_id', sa.Integer(), nullable=False, comment='课程ID'),
    sa.Column('select_time', sa.DateTime(), nullable=False, comment='选课时间'),
    sa.Column('status', sa.SmallInteger(), nullable=False, comment='1=已选 2=已退课'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id', 'course_id', name='uq_student_course')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('student_course')
    op.drop_table('score')
    op.drop_table('teacher_clazz')
    op.drop_table('student')
    op.drop_table('exam')
    op.drop_table('course')
    op.drop_table('clazz')
    op.drop_table('announcement_read')
    op.drop_table('user_role')
    op.drop_table('teacher')
    op.drop_table('role_menu')
    op.drop_table('operation_log')
    op.drop_table('announcement')
    op.drop_table('user')
    op.drop_table('role')
    op.drop_table('menu')
    op.drop_table('department')
    # ### end Alembic commands ###
